version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "StrongPassword123!"
      MSSQL_PID: Express
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - schoolmedical-network
    user: root

  # Redis Cache
  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "6379:6379"
    command: redis-server --requirepass Purejoy@123# --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - schoolmedical-network
    deploy:
      resources:
        limits:
          memory: 512M

  # School Medical Management System API
  schoolmedicalmanagementsystem.api:
    build:
      context: .
      dockerfile: SchoolMedicalManagementSystem.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "5200:5200"
      - "7280:7280"
    depends_on:
      - sqlserver
      - redis
    networks:
      - schoolmedical-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  schoolmedical-network:
    name: schoolmedical-network

volumes:
  sqlserver_data:
  redis_data: