version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "StrongPassword123!"
      MSSQL_PID: Express
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/init-db.sql
    networks:
      - schoolmedical-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'StrongPassword123!' -Q 'SELECT 1' -b -o /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "6379:6379"
    command: redis-server --requirepass Purejoy@123# --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - schoolmedical-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Purejoy@123#", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service tạo database
  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./init-db.sql:/init-db.sql
    networks:
      - schoolmedical-network
    command: >
      bash -c "
        echo 'Waiting for SQL Server to be ready...'
        sleep 5
        echo 'Creating database and tables...'
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'StrongPassword123!' -i /init-db.sql
        echo 'Database initialization completed!'
      "

  schoolmedicalmanagementsystem.api:
    build:
      context: .
      dockerfile: SchoolMedicalManagementSystem.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh
      - ALLOWED_ORIGINS=*
    ports:
      - "5200:5200"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - schoolmedical-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  schoolmedical-network:
    name: schoolmedical-network

volumes:
  sqlserver_data: