using SchoolMedicalManagementSystem.DataAccessLayer.Entities;

namespace SchoolMedicalManagementSystem.DataAccessLayer.RepositoryContracts;

public interface IStudentMedicationRepository : IBaseRepository<StudentMedicationAdministration>
{
}